package usecase

import (
	"context"
	"path/filepath"
	"strings"
	"testing"

	rootfs "mindfs/server/internal/fs"
)

func TestParseEnvironmentCommandsTOML(t *testing.T) {
	payload := []byte(`# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "demo-project"

[setup]
script = ""

[[actions]]
name = "运行开发"
icon = "run"
command = "npm run dev"

[[actions]]
name = "测试"
icon = "test"
command = "npm test"
`)
	parsed, err := parseEnvironmentCommandsTOML(payload)
	if err != nil {
		t.Fatalf("parseEnvironmentCommandsTOML() error = %v", err)
	}
	got := normalizeEnvironmentCommands(parsed.Commands)
	if len(got) != 2 {
		t.Fatalf("expected 2 commands, got %d", len(got))
	}
	if parsed.Name != "demo-project" {
		t.Fatalf("unexpected parsed name: %#v", parsed.Name)
	}
	if !got[0].IsDefault {
		t.Fatalf("unexpected first command: %#v", got[0])
	}
	if got[1].Icon != EnvironmentCommandIconTest {
		t.Fatalf("unexpected second icon: %#v", got[1])
	}
}

func TestMarshalEnvironmentCommandsTOMLRoundTrip(t *testing.T) {
	input := []EnvironmentCommand{
		{
			ID:        "abc",
			Name:      "Run \"Dev\"",
			Icon:      EnvironmentCommandIconRun,
			Command:   `npm run dev -- --flag="demo"`,
			IsDefault: true,
		},
	}
	payload := marshalEnvironmentCommandsTOML(environmentCommandsFile{
		Version:     1,
		Name:        "demo-project",
		SetupScript: "",
		Commands:    input,
	})
	if !strings.Contains(string(payload), `command = "npm run dev -- --flag=\"demo\""`) {
		t.Fatalf("marshalEnvironmentCommandsTOML() missing escaped command: %s", string(payload))
	}
	if strings.Contains(string(payload), `[[command]]`) || strings.Contains(string(payload), `default =`) {
		t.Fatalf("marshalEnvironmentCommandsTOML() wrote legacy format: %s", string(payload))
	}
	if !strings.Contains(string(payload), `[[actions]]`) || !strings.Contains(string(payload), `[setup]`) {
		t.Fatalf("marshalEnvironmentCommandsTOML() missing new sections: %s", string(payload))
	}
	parsed, err := parseEnvironmentCommandsTOML(payload)
	if err != nil {
		t.Fatalf("parseEnvironmentCommandsTOML() error = %v", err)
	}
	commands := normalizeEnvironmentCommands(parsed.Commands)
	if len(commands) != 1 || commands[0].Command != input[0].Command || commands[0].Name != input[0].Name {
		t.Fatalf("round-trip mismatch: %#v", commands)
	}
}

func TestSaveEnvironmentCommandWritesMetaFile(t *testing.T) {
	rootDir := t.TempDir()
	root := rootfs.NewRootInfo("demo", "demo", rootDir)
	service := &Service{Registry: uploadTestRegistry{root: root}}

	first, err := service.SaveEnvironmentCommand(context.Background(), SaveEnvironmentCommandInput{
		RootID:  root.ID,
		Name:    "运行开发",
		Icon:    "run",
		Command: "npm run dev",
	})
	if err != nil {
		t.Fatalf("SaveEnvironmentCommand(first) error = %v", err)
	}
	if len(first.Items) != 1 || !first.Items[0].IsDefault {
		t.Fatalf("unexpected first save output: %#v", first.Items)
	}

	second, err := service.SaveEnvironmentCommand(context.Background(), SaveEnvironmentCommandInput{
		RootID:     root.ID,
		Name:       "运行测试",
		Icon:       "test",
		Command:    "npm test",
		SetDefault: true,
	})
	if err != nil {
		t.Fatalf("SaveEnvironmentCommand(second) error = %v", err)
	}
	if len(second.Items) != 2 || !second.Items[1].IsDefault || second.Items[0].IsDefault {
		t.Fatalf("unexpected second save output: %#v", second.Items)
	}

	metaPayload, err := root.ReadMetaFile(filepath.ToSlash(environmentCommandsMetaPath))
	if err != nil {
		t.Fatalf("ReadMetaFile() error = %v", err)
	}
	if !strings.Contains(string(metaPayload), `name = "运行测试"`) {
		t.Fatalf("expected saved command in payload, got %s", string(metaPayload))
	}
	if !strings.Contains(string(metaPayload), `[[actions]]`) ||
		!strings.Contains(string(metaPayload), `name = "demo"`) ||
		!strings.Contains(string(metaPayload), `[setup]`) {
		t.Fatalf("expected new environment format, got %s", string(metaPayload))
	}
	if strings.Index(string(metaPayload), `name = "运行测试"`) > strings.Index(string(metaPayload), `name = "运行开发"`) {
		t.Fatalf("expected default action to be persisted first, got %s", string(metaPayload))
	}
	if strings.Contains(string(metaPayload), `[[command]]`) || strings.Contains(string(metaPayload), `default =`) {
		t.Fatalf("unexpected legacy keys in payload: %s", string(metaPayload))
	}
}

func TestBuildEnvironmentCommandScript(t *testing.T) {
	got := buildEnvironmentCommandScript(`D:\demo\that's`, "npm run dev")
	want := `[Console]::InputEncoding = [System.Text.Encoding]::UTF8; [Console]::OutputEncoding = [System.Text.Encoding]::UTF8; $OutputEncoding = [System.Text.Encoding]::UTF8; Set-Location -LiteralPath 'D:\demo\that''s'; npm run dev`
	if got != want {
		t.Fatalf("buildEnvironmentCommandScript() = %q, want %q", got, want)
	}
}
